### ISSUE TITLE
Version 3.0.0 uses two different OT API versions causing NoSuchMethodError

### ISSUE THREAD

**Issue by JingangLi** [opentracing-contrib/java-spring-jaeger#85]
Hi,

I use opentracing-spring-jaeger-web-starter:3.0.0 and faces the below issue `java.lang.NoSuchMethodError: io.opentracing.Scope.span()Lio/opentracing/Span`. 

When I use opentracing-spring-jaeger-cloud-starter version:2.0.2, the issue disappear. 

I think the issue is because of in opentracing-spring-jaeger-web-starter:3.0.0, the opentracing-util-0.32.0.jar is mixed use with opentracing-api-0.33.0.jar. I found in opentracing-api-0.33.0.jar, the Scope.span is removed from opentracing.scope class. So far I don't why this happens, it should be somewhere in opentracing-spring-jaeger-web-starter:3.0.0, I guess.

`java.lang.NoSuchMethodError: io.opentracing.Scope.span()Lio/opentracing/Span; at io.opentracing.util.ThreadLocalScopeManager.activeSpan(ThreadLocalScopeManager.java:46) ~[opentracing-util-0.32.0.jar:na] at io.jaegertracing.internal.JaegerTracer.activeSpan(JaegerTracer.java:194) ~[jaeger-core-1.1.0.jar:1.1.0] at io.opentracing.contrib.spring.cloud.log.SpanLogsAppender.append(SpanLogsAppender.java:46) ~[opentracing-spring-cloud-core-0.3.0.jar:na] at io.opentracing.contrib.spring.cloud.log.SpanLogsAppender.append(SpanLogsAppender.java:31) ~[opentracing-spring-cloud-core-0.3.0.jar:na] at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84) ~[logback-core-1.2.3.jar:na]`

**Comment by pavolloffay** [comment]
Could you please post `mvn dependency:tree` ?

**Comment by JingangLi** [comment]
> Could you please post `mvn dependency:tree` ?

Hi @pavolloffay , 

This is the dependency informaiton: 

> \- io.opentracing.contrib:opentracing-spring-jaeger-cloud-starter:jar:3.0.0:compile
>    +- io.opentracing.contrib:opentracing-spring-jaeger-starter:jar:3.0.0:compile
>       +- io.opentracing.contrib:opentracing-spring-tracer-configuration-starter:jar:0.2.0:compile
>          +- io.opentracing:opentracing-noop:jar:0.32.0:compile
>          +- io.opentracing:opentracing-util:jar:**0.32.0**:compile
>          \- io.opentracing.contrib:opentracing-tracerresolver:jar:0.1.6:compile
>       +- io.opentracing:opentracing-api:jar:**0.33.0**:compile

And this is my pom:

> 		<dependency>
>   		  <groupId>io.opentracing.contrib</groupId>
>   		  <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
> 		  <version>3.0.0</version>
> 		</dependency>

**Comment by LinhVu1027** [comment]
Maybe you used Hoxton spring-cloud.version. So the opentracing-spring-cloud-starter 0.3.0 followed by opentracing-spring-jaeger-cloud-starter 3.0.0 is not compatible. You might add the opentracing-spring-cloud-starter 0.4.0.

**Comment by breucode** [comment]
I faced a very similar error today `"NoSuchMethodError": io.opentracing.Scope io.opentracing.Tracer$SpanBuilder.startActive(boolean)`

The problem is definitely two conflicting versions of io.opentracing:opentracing-api.

![image](https://user-images.githubusercontent.com/3304638/76331432-6f2ac080-62ef-11ea-856c-00d6a60b2519.png)

When forcing io.opentracing:opentracing-api to be version 0.32.0, the following error occurs:
`java.lang.AbstractMethodError: Receiver class io.opentracing.noop.NoopSpanBuilderImpl does not define or inherit an implementation of the resolved method 'abstract io.opentracing.Scope startActive(boolean)' of interface io.opentracing.Tracer$SpanBuilder`

**Comment by JingangLi** [comment]
> Maybe you used Hoxton spring-cloud.version. So the opentracing-spring-cloud-starter 0.3.0 followed by opentracing-spring-jaeger-cloud-starter 3.0.0 is not compatible. You might add the opentracing-spring-cloud-starter 0.4.0.

Hi @LinhVu1027 ,
Thanks for your comments. It works for me.  Is there some other way can handle this better? Maybe I should close the ticket,

@breucode , I try to use opentracing-spring-cloud-starter:0.5.0, which is the latest version. But it still use 0.32.0. And it doesn't work well in my spring boot version. So I skip it.

**Comment by pavolloffay** [comment]
@geoand this project pulls in mixed versions of OpenTracing API wich is causing runtime exceptions due to breaking changes in OT API.

`opentracing-spring-jaeger-starter` is pulling in OT spring cloud instrumentation with version 0.32.0 and it should be 0.33.0. The depdendency should be updated to `0.5.x` https://github.com/opentracing-contrib/java-spring-cloud

**Comment by geoand** [comment]
Version `3.1.0` has been released which bumps https://github.com/opentracing-contrib/java-spring-cloud to `0.5.0` and thus fixes the problem

**Comment by LinhVu1027** [comment]
@geoand 
<img width="703" alt="Screen Shot 2020-03-12 at 3 21 00 PM" src="https://user-images.githubusercontent.com/17743073/76501583-1b49e400-6475-11ea-892a-bb174f6c6c5b.png">
I saw the version of opentracing-util was still 0.32.0, while opentracing-api is 0.33.0. And I face the problem:
 `java.lang.NoSuchMethodError: io.opentracing.Scope.span()Lio/opentracing/Span;
	at io.opentracing.util.ThreadLocalScopeManager.activeSpan(ThreadLocalScopeManager.java:46) ~[opentracing-util-0.32.0.jar:na]
	at io.jaegertracing.internal.JaegerTracer.activeSpan(JaegerTracer.java:194) ~[jaeger-core-1.1.0.jar:1.1.0]
	at io.opentracing.contrib.spring.cloud.log.SpanLogsAppender.append(SpanLogsAppender.java:46) ~[opentracing-spring-cloud-core-0.5.0.jar:na]
	at io.opentracing.contrib.spring.cloud.log.SpanLogsAppender.append(SpanLogsAppender.java:31) ~[opentracing-spring-cloud-core-0.5.0.jar:na]
`
Caused by activeSpan() method in ThreadLocalScopeManager in util 0.32.0 wasn't compatible with Scope interface in api 0.33.0.

**Comment by LinhVu1027** [comment]
Version `3.1.1` solved this.

**Comment by geoand** [comment]
Excellent, thanks for your PR
